import React from 'react';
import { Activity, CheckCircle2, Database, FileCheck2, LockKeyhole, ShieldCheck, Users } from 'lucide-react';
import SchemaReference from './SchemaReference';

const roles = [
  ['Administrator', 'Full platform administration', ['Query generation', 'Query execution', 'Global audit access', 'User management']],
  ['Data Engineer', 'Data and schema operations', ['Query generation', 'Query execution', 'Advanced analytics']],
  ['Power User', 'Managed data operations', ['Query generation', 'Query execution']],
  ['Auditor', 'Read-only governance review', ['Global audit access']],
  ['Viewer', 'Read-only workspace access', []],
];
const Metric = ({ icon: Icon, label, value, detail }) => <div className="metric-card"><span className="metric-icon"><Icon size={18}/></span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></div>;

export default function EnterpriseViews({ type, user, role, onOpenStudio }) {
  if (type === 'overview') return <><div className="welcome-row"><div><h2>Good morning, {user.first_name || 'there'}.</h2><p>Here’s what’s happening across your data workspace.</p></div><button className="btn btn-primary" onClick={onOpenStudio}>Open AI Query Studio</button></div><div className="metrics-grid"><Metric icon={Activity} label="Queries Executed" value="1,248" detail="Demo workspace metric"/><Metric icon={Users} label="Active Users" value="32" detail="Demo workspace metric"/><Metric icon={CheckCircle2} label="Success Rate" value="97.4%" detail="Last 30 days"/><Metric icon={LockKeyhole} label="Blocked Queries" value="18" detail="Safety layer decisions"/></div><div className="overview-grid"><section className="content-card chart-card"><p className="eyebrow">Activity</p><h3>Query activity over time</h3><div className="chart-placeholder"><i/><i/><i/><i/><i/><i/><i/></div><p className="muted">Usage analytics will reflect live activity when the analytics API is connected.</p></section><section className="content-card"><p className="eyebrow">System health</p><h3>Platform controls</h3><div className="control-list"><span><CheckCircle2/> AI Model <b>Connected</b></span><span><CheckCircle2/> Database <b>Connected</b></span><span><CheckCircle2/> Safety Layer <b>Active</b></span><span><CheckCircle2/> Access Policy <b>Enforced</b></span></div></section></div></>;
  if (type === 'explorer') return <div className="explorer-page"><div className="source-card"><div><Database/><div><p className="eyebrow">Connected source</p><h2>College Demo Database</h2><span>SQLite Database · Development environment</span></div></div><b><span className="status-dot"/> Connected</b></div><p className="page-lead">Discover the structure of connected enterprise data sources.</p><SchemaReference /></div>;
  if (type === 'audit') return <><div className="section-heading"><p className="eyebrow">Governance center</p><h2>Monitor AI-generated queries and access decisions</h2><p>Global audit values are demo metrics until the audit API is connected.</p></div><div className="metrics-grid"><Metric icon={Activity} label="Total Requests" value="12,480" detail="Demo metric"/><Metric icon={CheckCircle2} label="Approved" value="11,940" detail="Demo metric"/><Metric icon={ShieldCheck} label="Blocked" value="420" detail="Demo metric"/><Metric icon={FileCheck2} label="Failed" value="120" detail="Demo metric"/></div><div className="content-card empty-state"><FileCheck2 size={26}/><h3>Audit log integration ready</h3><p>The current API only returns personal query history. Add a protected global audit endpoint to populate this view.</p></div></>;
  if (type === 'access') return <><div className="section-heading"><p className="eyebrow">Role-based access control</p><h2>Permission profiles</h2><p>Roles are enforced by the backend for query execution and user management.</p></div><div className="role-grid">{roles.map(([name, description, permissions]) => <article className="role-card" key={name}><ShieldCheck/><h3>{name}</h3><p>{description}</p>{permissions.length ? permissions.map(p => <span key={p}><CheckCircle2 size={14}/>{p}</span>) : <span className="muted">Read-only profile</span>}</article>)}</div></>;
  if (type === 'profile') return <div className="profile-grid"><section className="content-card"><p className="eyebrow">Personal information</p><h2>{user.first_name || 'Workspace'} {user.last_name || 'User'}</h2><p>{user.email}</p></section><section className="content-card"><p className="eyebrow">Access & security</p><div className="control-list"><span><ShieldCheck/> Assigned role <b>{role}</b></span><span><CheckCircle2/> Account status <b>{user.is_active ? 'Active' : 'Inactive'}</b></span><span><LockKeyhole/> Authentication <b>JWT</b></span></div></section></div>;
  return null;
}
